### PR TITLE
Add GH Actions for `yarn rw lint` &&`yarn rw test`

### PR DESCRIPTION
**Pull request by thedavidprice**
Depends on 
- [x] redwoodjs/redwood/pull/152
- [x] redwoodjs/redwood/pull/185
- [ ] need resolution of redwoodjs/redwood#265

~~Runs against Node 10 and 12 latest.~~ Just node 12, but ready for matrix run when 14 is released May 1.

Wait to confirm generators and tests are running well as is [DONE] 
- [ ] confirm all generator test templates can pass
- [x] confirm linter passes out of the box

### CODE REVIEW

**Comment by thedavidprice** [comment]
@peterp @cannikin the GitHub Action for the CRA app, which runs `yarn rw lint` and `yarn rw test`, is now ready to go. There is a linter warning that’s been resolved in a PR to @redwoodjs already merged but not yet published. These tests are meant for users building an app. The test templates for each generator will pass out of the box. 

Any thoughts or edits before we merge?

Next we will need to think about how/if we run our own tests for development and how to configure those separately. As of right now these Actions _will_ run when we PR. Conceivably we could create our tests for development but strip them out during the CRA bootstrap. TBD

Passing test with two generated components:
Screen Shot 2020-03-14 at 10 03 54 PM


Passing linter (note: warning already handled in @redwoodjs repo):
Screen Shot 2020-03-14 at 10 04 20 PM

**Comment by thedavidprice** [comment]
HOLD: this needs to wait until resolution of redwoodjs/redwood#265

**Comment by thedavidprice** [comment]
hold until dependency is resolved

**Review by peterp — APPROVED** [review]

**Comment by thedavidprice** [comment]
Almost! Still issues with redwoodjs/redwood#265 that will just add to confusion if we merge now.

**Pull request closed without merging**
